GENERATOR_SIMILAR_INTERESTS = "generateSimilarInterests"
METADATA_FIELD_SCORE_SIMILAR_INTERESTS = "score"
METADATA_FIELD_COMMON_SIMILAR_INTERESTS = "commonInterests"

# TODO: Implement your generator
